name: Docker Image CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:        
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Set variables
          id: vars
          run: |
            echo "sha_short=$(git log -1 --format=%h)" >> $GITHUB_OUTPUT
            echo "image_tag=${{ secrets.AZURE_REGISTRY_LOGIN }}/outfitapp:$(git log -1 --format=%h)" >> $GITHUB_OUTPUT
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image to Azure Container Registry'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.AZURE_REGISTRY_LOGIN }}
            username: ${{ secrets.AZURE_REGISTRY_LOGIN_USERNAME }}
            password: ${{ secrets.AZURE_REGISTRY_LOGIN_PASSWORD }}
        - run: |
            docker build ./outfitapp -t ${{ steps.vars.outputs.image_tag }}
            docker push ${{ steps.vars.outputs.image_tag }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ steps.vars.outputs.sha_short }}
            image: ${{ steps.vars.outputs.image_tag }}
            registry-login-server: ${{ secrets.AZURE_REGISTRY_LOGIN }}
            registry-username: ${{ secrets.AZURE_REGISTRY_LOGIN_USERNAME }}
            registry-password: ${{ secrets.AZURE_REGISTRY_LOGIN_PASSWORD }}
            secure-environment-variables: |
              AZURE_SQL_CONNECTIONSTRING_EUNORTH="${{ secrets.EUNORTH_CONNECTIONSTRING }}"
              AZURE_SQL_CONNECTIONSTRING_ASIAEAST="${{ secrets.ASIAEAST_CONNECTIONSTRING }}"
              AZURE_SQL_CONNECTIONSTRING_USWEST="${{ secrets.USWEST_CONNECTIONSTRING }}"
            ports: 80
            restart-policy: 'OnFailure'
            name: 'outfitapp'
            location: 'northeurope'
